### ISSUE TITLE
Malformed BlasterS-2 - g1309 group

### ISSUE THREAD

**Issue by drom** [gchapyzh/Legion#2]
First module in the document looks malformed.
```xml
<g
       transform="translate(160,80)"
       id="BlasterS-2" />
    <g
       id="g1309">
      <rect
         y="204.50391"
         x="840"
...
```

**Comment by drom** [comment]
My Guess is:
  * `h1309` - is backup stuff -- and should be renamed into `Backup1` or something with known prefix
  * `BlasterS-2` - empty leftover group

**Comment by gchapyzh** [comment]
Fixed
